### ISSUE TITLE
Implementation progress

### ISSUE THREAD

**Issue by HrsPythonix** [Debapriya-Tula/Video-inbetweening#1]
Is it able to train the video in-between mode now?

**Comment by Debapriya-Tula** [comment]
No, I am sorry for that. I was stuck with the discriminator loss. I couldn't understand it. Later on, I found a more suitable approach to my primary problem which was to **reconstruct** the frames in between, not **generate** as in a Generator would do, Please find my other repo viz, [AdaConvPytorch](https://github.com/Debapriya-Tula/AdaConv-Pytorch) which better suits my problem. It is based on a GitHub code by Hyeongmin Lee. I have modified the code for the Visual Tracker Benchmark dataset.

P.S. I am no longer working on this repo.

**Comment by HrsPythonix** [comment]
got it, thank you for your quick response
